export interface TimeZoneData {
  id: string
  city: string
  identifier: string
  label: string
  emoji: string
}

export const availableTimeZones: TimeZoneData[] = [
  // North America
  { id: 'ny', city: 'New York', identifier: 'America/New_York', label: '', emoji: '🗽' },
  { id: 'la', city: 'Los Angeles', identifier: 'America/Los_Angeles', label: '', emoji: '🌴' },
  { id: 'sf', city: 'San Francisco', identifier: 'America/Los_Angeles', label: '', emoji: '🌉' },
  { id: 'chicago', city: 'Chicago', identifier: 'America/Chicago', label: '', emoji: '🌆' },
  { id: 'denver', city: 'Denver', identifier: 'America/Denver', label: '', emoji: '⛰️' },
  { id: 'phoenix', city: 'Phoenix', identifier: 'America/Phoenix', label: '', emoji: '🌵' },
  { id: 'seattle', city: 'Seattle', identifier: 'America/Los_Angeles', label: '', emoji: '🌲' },
  { id: 'miami', city: 'Miami', identifier: 'America/New_York', label: '', emoji: '🏖️' },
  { id: 'boston', city: 'Boston', identifier: 'America/New_York', label: '', emoji: '🦞' },
  { id: 'atlanta', city: 'Atlanta', identifier: 'America/New_York', label: '', emoji: '🍑' },
  { id: 'toronto', city: 'Toronto', identifier: 'America/Toronto', label: '', emoji: '🍁' },
  { id: 'vancouver', city: 'Vancouver', identifier: 'America/Vancouver', label: '', emoji: '🏔️' },
  { id: 'mexico-city', city: 'Mexico City', identifier: 'America/Mexico_City', label: '', emoji: '🌮' },

  // South America
  { id: 'sao-paulo', city: 'São Paulo', identifier: 'America/Sao_Paulo', label: '', emoji: '🇧🇷' },
  { id: 'buenos-aires', city: 'Buenos Aires', identifier: 'America/Argentina/Buenos_Aires', label: '', emoji: '⚽' },
  { id: 'rio', city: 'Rio de Janeiro', identifier: 'America/Sao_Paulo', label: '', emoji: '🏖️' },

  // Europe
  { id: 'london', city: 'London', identifier: 'Europe/London', label: '', emoji: '🏰' },
  { id: 'paris', city: 'Paris', identifier: 'Europe/Paris', label: '', emoji: '🗼' },
  { id: 'berlin', city: 'Berlin', identifier: 'Europe/Berlin', label: '', emoji: '🏛️' },
  { id: 'madrid', city: 'Madrid', identifier: 'Europe/Madrid', label: '', emoji: '🇪🇸' },
  { id: 'rome', city: 'Rome', identifier: 'Europe/Rome', label: '', emoji: '🏛️' },
  { id: 'amsterdam', city: 'Amsterdam', identifier: 'Europe/Amsterdam', label: '', emoji: '🇳🇱' },
  { id: 'moscow', city: 'Moscow', identifier: 'Europe/Moscow', label: '', emoji: '🏛️' },
  { id: 'istanbul', city: 'Istanbul', identifier: 'Europe/Istanbul', label: '', emoji: '🕌' },
  { id: 'dublin', city: 'Dublin', identifier: 'Europe/Dublin', label: '', emoji: '🍀' },

  // Asia
  { id: 'tokyo', city: 'Tokyo', identifier: 'Asia/Tokyo', label: '', emoji: '🗼' },
  { id: 'seoul', city: 'Seoul', identifier: 'Asia/Seoul', label: '', emoji: '🇰🇷' },
  { id: 'beijing', city: 'Beijing', identifier: 'Asia/Shanghai', label: '', emoji: '🇨🇳' },
  { id: 'shanghai', city: 'Shanghai', identifier: 'Asia/Shanghai', label: '', emoji: '🏙️' },
  { id: 'hong-kong', city: 'Hong Kong', identifier: 'Asia/Hong_Kong', label: '', emoji: '🏙️' },
  { id: 'singapore', city: 'Singapore', identifier: 'Asia/Singapore', label: '', emoji: '🦁' },
  { id: 'bangkok', city: 'Bangkok', identifier: 'Asia/Bangkok', label: '', emoji: '🛕' },
  { id: 'dubai', city: 'Dubai', identifier: 'Asia/Dubai', label: '', emoji: '🏜️' },
  { id: 'mumbai', city: 'Mumbai', identifier: 'Asia/Kolkata', label: '', emoji: '🕌' },
  { id: 'delhi', city: 'Delhi', identifier: 'Asia/Kolkata', label: '', emoji: '🇮🇳' },

  // Oceania
  { id: 'sydney', city: 'Sydney', identifier: 'Australia/Sydney', label: '', emoji: '🦘' },
  { id: 'melbourne', city: 'Melbourne', identifier: 'Australia/Melbourne', label: '', emoji: '🏙️' },
  { id: 'auckland', city: 'Auckland', identifier: 'Pacific/Auckland', label: '', emoji: '🥝' },

  // World Capitals
  { id: 'abu-dhabi', city: 'Abu Dhabi', identifier: 'Asia/Dubai', label: '', emoji: '🏛️' },
  { id: 'abj', city: 'Abuja', identifier: 'Africa/Lagos', label: '', emoji: '🏛️' },
  { id: 'accra', city: 'Accra', identifier: 'Africa/Accra', label: '', emoji: '🏛️' },
  { id: 'addis-ababa', city: 'Addis Ababa', identifier: 'Africa/Addis_Ababa', label: '', emoji: '🏛️' },
  { id: 'algiers', city: 'Algiers', identifier: 'Africa/Algiers', label: '', emoji: '🏛️' },
  { id: 'amman', city: 'Amman', identifier: 'Asia/Amman', label: '', emoji: '🏛️' },
  { id: 'amsterdam-capital', city: 'Amsterdam', identifier: 'Europe/Amsterdam', label: '', emoji: '🏛️' },
  { id: 'andorra-la-vella', city: 'Andorra la Vella', identifier: 'Europe/Andorra', label: '', emoji: '🏛️' },
  { id: 'ankara', city: 'Ankara', identifier: 'Europe/Istanbul', label: '', emoji: '🏛️' },
  { id: 'antananarivo', city: 'Antananarivo', identifier: 'Indian/Antananarivo', label: '', emoji: '🏛️' },
  { id: 'apia', city: 'Apia', identifier: 'Pacific/Apia', label: '', emoji: '🏛️' },
  { id: 'ashgabat', city: 'Ashgabat', identifier: 'Asia/Ashgabat', label: '', emoji: '🏛️' },
  { id: 'asmara', city: 'Asmara', identifier: 'Africa/Asmara', label: '', emoji: '🏛️' },
  { id: 'astana', city: 'Astana', identifier: 'Asia/Almaty', label: '', emoji: '🏛️' },
  { id: 'athens', city: 'Athens', identifier: 'Europe/Athens', label: '', emoji: '🏛️' },
  { id: 'baghdad', city: 'Baghdad', identifier: 'Asia/Baghdad', label: '', emoji: '🏛️' },
  { id: 'baku', city: 'Baku', identifier: 'Asia/Baku', label: '', emoji: '🏛️' },
  { id: 'bamako', city: 'Bamako', identifier: 'Africa/Bamako', label: '', emoji: '🏛️' },
  { id: 'bandar-seri-begawan', city: 'Bandar Seri Begawan', identifier: 'Asia/Brunei', label: '', emoji: '🏛️' },
  { id: 'bangui', city: 'Bangui', identifier: 'Africa/Bangui', label: '', emoji: '🏛️' },
  { id: 'banjul', city: 'Banjul', identifier: 'Africa/Banjul', label: '', emoji: '🏛️' },
  { id: 'basseterre', city: 'Basseterre', identifier: 'America/St_Kitts', label: '', emoji: '🏛️' },
  { id: 'beirut', city: 'Beirut', identifier: 'Asia/Beirut', label: '', emoji: '🏛️' },
  { id: 'belmopan', city: 'Belmopan', identifier: 'America/Belize', label: '', emoji: '🏛️' },
  { id: 'bern', city: 'Bern', identifier: 'Europe/Zurich', label: '', emoji: '🏛️' },
  { id: 'bissau', city: 'Bissau', identifier: 'Africa/Bissau', label: '', emoji: '🏛️' },
  { id: 'bogota', city: 'Bogotá', identifier: 'America/Bogota', label: '', emoji: '🏛️' },
  { id: 'brasilia', city: 'Brasília', identifier: 'America/Sao_Paulo', label: '', emoji: '🏛️' },
  { id: 'bratislava', city: 'Bratislava', identifier: 'Europe/Bratislava', label: '', emoji: '🏛️' },
  { id: 'bridgetown', city: 'Bridgetown', identifier: 'America/Barbados', label: '', emoji: '🏛️' },
  { id: 'brussels', city: 'Brussels', identifier: 'Europe/Brussels', label: '', emoji: '🏛️' },
  { id: 'bucharest', city: 'Bucharest', identifier: 'Europe/Bucharest', label: '', emoji: '🏛️' },
  { id: 'budapest', city: 'Budapest', identifier: 'Europe/Budapest', label: '', emoji: '🏛️' },
  { id: 'buenos-aires-capital', city: 'Buenos Aires', identifier: 'America/Argentina/Buenos_Aires', label: '', emoji: '🏛️' },
  { id: 'cairo', city: 'Cairo', identifier: 'Africa/Cairo', label: '', emoji: '🏛️' },
  { id: 'canberra', city: 'Canberra', identifier: 'Australia/Canberra', label: '', emoji: '🏛️' },
  { id: 'caracas', city: 'Caracas', identifier: 'America/Caracas', label: '', emoji: '🏛️' },
  { id: 'castries', city: 'Castries', identifier: 'America/St_Lucia', label: '', emoji: '🏛️' },
  { id: 'chisinau', city: 'Chișinău', identifier: 'Europe/Chisinau', label: '', emoji: '🏛️' },
  { id: 'conakry', city: 'Conakry', identifier: 'Africa/Conakry', label: '', emoji: '🏛️' },
  { id: 'copenhagen', city: 'Copenhagen', identifier: 'Europe/Copenhagen', label: '', emoji: '🏛️' },
  { id: 'dakar', city: 'Dakar', identifier: 'Africa/Dakar', label: '', emoji: '🏛️' },
  { id: 'damascus', city: 'Damascus', identifier: 'Asia/Damascus', label: '', emoji: '🏛️' },
  { id: 'dhaka', city: 'Dhaka', identifier: 'Asia/Dhaka', label: '', emoji: '🏛️' },
  { id: 'dili', city: 'Dili', identifier: 'Asia/Dili', label: '', emoji: '🏛️' },
  { id: 'djibouti', city: 'Djibouti', identifier: 'Africa/Djibouti', label: '', emoji: '🏛️' },
  { id: 'dodoma', city: 'Dodoma', identifier: 'Africa/Dar_es_Salaam', label: '', emoji: '🏛️' },
  { id: 'doha', city: 'Doha', identifier: 'Asia/Qatar', label: '', emoji: '🏛️' },
  { id: 'dublin-capital', city: 'Dublin', identifier: 'Europe/Dublin', label: '', emoji: '🏛️' },
  { id: 'dushanbe', city: 'Dushanbe', identifier: 'Asia/Dushanbe', label: '', emoji: '🏛️' },
  { id: 'edinburgh', city: 'Edinburgh', identifier: 'Europe/London', label: '', emoji: '🏛️' },
  { id: 'freetown', city: 'Freetown', identifier: 'Africa/Freetown', label: '', emoji: '🏛️' },
  { id: 'funafuti', city: 'Funafuti', identifier: 'Pacific/Funafuti', label: '', emoji: '🏛️' },
  { id: 'gaborone', city: 'Gaborone', identifier: 'Africa/Gaborone', label: '', emoji: '🏛️' },
  { id: 'georgetown', city: 'Georgetown', identifier: 'America/Guyana', label: '', emoji: '🏛️' },
  { id: 'guatemala-city', city: 'Guatemala City', identifier: 'America/Guatemala', label: '', emoji: '🏛️' },
  { id: 'hanoi', city: 'Hanoi', identifier: 'Asia/Bangkok', label: '', emoji: '🏛️' },
  { id: 'harare', city: 'Harare', identifier: 'Africa/Harare', label: '', emoji: '🏛️' },
  { id: 'havana', city: 'Havana', identifier: 'America/Havana', label: '', emoji: '🏛️' },
  { id: 'helsinki', city: 'Helsinki', identifier: 'Europe/Helsinki', label: '', emoji: '🏛️' },
  { id: 'honiara', city: 'Honiara', identifier: 'Pacific/Guadalcanal', label: '', emoji: '🏛️' },
  { id: 'islamabad', city: 'Islamabad', identifier: 'Asia/Karachi', label: '', emoji: '🏛️' },
  { id: 'jakarta', city: 'Jakarta', identifier: 'Asia/Jakarta', label: '', emoji: '🏛️' },
  { id: 'jerusalem', city: 'Jerusalem', identifier: 'Asia/Jerusalem', label: '', emoji: '🏛️' },
  { id: 'kabul', city: 'Kabul', identifier: 'Asia/Kabul', label: '', emoji: '🏛️' },
  { id: 'kampala', city: 'Kampala', identifier: 'Africa/Kampala', label: '', emoji: '🏛️' },
  { id: 'kathmandu', city: 'Kathmandu', identifier: 'Asia/Kathmandu', label: '', emoji: '🏛️' },
  { id: 'khartoum', city: 'Khartoum', identifier: 'Africa/Khartoum', label: '', emoji: '🏛️' },
  { id: 'kigali', city: 'Kigali', identifier: 'Africa/Kigali', label: '', emoji: '🏛️' },
  { id: 'kingston', city: 'Kingston', identifier: 'America/Jamaica', label: '', emoji: '🏛️' },
  { id: 'kingstown', city: 'Kingstown', identifier: 'America/St_Vincent', label: '', emoji: '🏛️' },
  { id: 'kinshasa', city: 'Kinshasa', identifier: 'Africa/Kinshasa', label: '', emoji: '🏛️' },
  { id: 'kyiv', city: 'Kyiv', identifier: 'Europe/Kyiv', label: '', emoji: '🏛️' },
  { id: 'la-paz', city: 'La Paz', identifier: 'America/La_Paz', label: '', emoji: '🏛️' },
  { id: 'libreville', city: 'Libreville', identifier: 'Africa/Libreville', label: '', emoji: '🏛️' },
  { id: 'lilongwe', city: 'Lilongwe', identifier: 'Africa/Blantyre', label: '', emoji: '🏛️' },
  { id: 'lisbon', city: 'Lisbon', identifier: 'Europe/Lisbon', label: '', emoji: '🏛️' },
  { id: 'ljubljana', city: 'Ljubljana', identifier: 'Europe/Ljubljana', label: '', emoji: '🏛️' },
  { id: 'lome', city: 'Lomé', identifier: 'Africa/Lome', label: '', emoji: '🏛️' },
  { id: 'lusaka', city: 'Lusaka', identifier: 'Africa/Lusaka', label: '', emoji: '🏛️' },
  { id: 'luxembourg', city: 'Luxembourg', identifier: 'Europe/Luxembourg', label: '', emoji: '🏛️' },
  { id: 'madrid-capital', city: 'Madrid', identifier: 'Europe/Madrid', label: '', emoji: '🏛️' },
  { id: 'majuro', city: 'Majuro', identifier: 'Pacific/Majuro', label: '', emoji: '🏛️' },
  { id: 'male', city: 'Malé', identifier: 'Indian/Maldives', label: '', emoji: '🏛️' },
  { id: 'managua', city: 'Managua', identifier: 'America/Managua', label: '', emoji: '🏛️' },
  { id: 'manama', city: 'Manama', identifier: 'Asia/Bahrain', label: '', emoji: '🏛️' },
  { id: 'maputo', city: 'Maputo', identifier: 'Africa/Maputo', label: '', emoji: '🏛️' },
  { id: 'maseru', city: 'Maseru', identifier: 'Africa/Maseru', label: '', emoji: '🏛️' },
  { id: 'mbabane', city: 'Mbabane', identifier: 'Africa/Mbabane', label: '', emoji: '🏛️' },
  { id: 'mexico-city-capital', city: 'Mexico City', identifier: 'America/Mexico_City', label: '', emoji: '🏛️' },
  { id: 'minsk', city: 'Minsk', identifier: 'Europe/Minsk', label: '', emoji: '🏛️' },
  { id: 'mogadishu', city: 'Mogadishu', identifier: 'Africa/Mogadishu', label: '', emoji: '🏛️' },
  { id: 'monaco', city: 'Monaco', identifier: 'Europe/Monaco', label: '', emoji: '🏛️' },
  { id: 'monrovia', city: 'Monrovia', identifier: 'Africa/Monrovia', label: '', emoji: '🏛️' },
  { id: 'montevideo', city: 'Montevideo', identifier: 'America/Montevideo', label: '', emoji: '🏛️' },
  { id: 'moscow-capital', city: 'Moscow', identifier: 'Europe/Moscow', label: '', emoji: '🏛️' },
  { id: 'muscat', city: 'Muscat', identifier: 'Asia/Muscat', label: '', emoji: '🏛️' },
  { id: 'nairobi', city: 'Nairobi', identifier: 'Africa/Nairobi', label: '', emoji: '🏛️' },
  { id: 'nassau', city: 'Nassau', identifier: 'America/Nassau', label: '', emoji: '🏛️' },
  { id: 'nDjamena', city: "N'Djamena", identifier: 'Africa/Ndjamena', label: '', emoji: '🏛️' },
  { id: 'niamey', city: 'Niamey', identifier: 'Africa/Niamey', label: '', emoji: '🏛️' },
  { id: 'nicosia', city: 'Nicosia', identifier: 'Asia/Nicosia', label: '', emoji: '🏛️' },
  { id: 'nouakchott', city: 'Nouakchott', identifier: 'Africa/Nouakchott', label: '', emoji: '🏛️' },
  { id: 'nuku-alofa', city: "Nuku'alofa", identifier: 'Pacific/Tongatapu', label: '', emoji: '🏛️' },
  { id: 'oslo', city: 'Oslo', identifier: 'Europe/Oslo', label: '', emoji: '🏛️' },
  { id: 'ottawa', city: 'Ottawa', identifier: 'America/Toronto', label: '', emoji: '🏛️' },
  { id: 'ouagadougou', city: 'Ouagadougou', identifier: 'Africa/Ouagadougou', label: '', emoji: '🏛️' },
  { id: 'palikir', city: 'Palikir', identifier: 'Pacific/Pohnpei', label: '', emoji: '🏛️' },
  { id: 'panama-city', city: 'Panama City', identifier: 'America/Panama', label: '', emoji: '🏛️' },
  { id: 'paramaribo', city: 'Paramaribo', identifier: 'America/Paramaribo', label: '', emoji: '🏛️' },
  { id: 'phnom-penh', city: 'Phnom Penh', identifier: 'Asia/Phnom_Penh', label: '', emoji: '🏛️' },
  { id: 'podgorica', city: 'Podgorica', identifier: 'Europe/Podgorica', label: '', emoji: '🏛️' },
  { id: 'port-au-prince', city: 'Port-au-Prince', identifier: 'America/Port-au-Prince', label: '', emoji: '🏛️' },
  { id: 'port-louis', city: 'Port Louis', identifier: 'Indian/Mauritius', label: '', emoji: '🏛️' },
  { id: 'port-moresby', city: 'Port Moresby', identifier: 'Pacific/Port_Moresby', label: '', emoji: '🏛️' },
  { id: 'port-of-spain', city: 'Port of Spain', identifier: 'America/Port_of_Spain', label: '', emoji: '🏛️' },
  { id: 'porto-novo', city: 'Porto-Novo', identifier: 'Africa/Porto-Novo', label: '', emoji: '🏛️' },
  { id: 'prague', city: 'Prague', identifier: 'Europe/Prague', label: '', emoji: '🏛️' },
  { id: 'pretoria', city: 'Pretoria', identifier: 'Africa/Johannesburg', label: '', emoji: '🏛️' },
  { id: 'pyongyang', city: 'Pyongyang', identifier: 'Asia/Pyongyang', label: '', emoji: '🏛️' },
  { id: 'quito', city: 'Quito', identifier: 'America/Guayaquil', label: '', emoji: '🏛️' },
  { id: 'rabat', city: 'Rabat', identifier: 'Africa/Casablanca', label: '', emoji: '🏛️' },
  { id: 'reykjavik', city: 'Reykjavík', identifier: 'Atlantic/Reykjavik', label: '', emoji: '🏛️' },
  { id: 'riga', city: 'Riga', identifier: 'Europe/Riga', label: '', emoji: '🏛️' },
  { id: 'riyadh', city: 'Riyadh', identifier: 'Asia/Riyadh', label: '', emoji: '🏛️' },
  { id: 'rome-capital', city: 'Rome', identifier: 'Europe/Rome', label: '', emoji: '🏛️' },
  { id: 'roseau', city: 'Roseau', identifier: 'America/Dominica', label: '', emoji: '🏛️' },
  { id: 'san-jose', city: 'San José', identifier: 'America/Costa_Rica', label: '', emoji: '🏛️' },
  { id: 'san-marino', city: 'San Marino', identifier: 'Europe/San_Marino', label: '', emoji: '🏛️' },
  { id: 'san-salvador', city: 'San Salvador', identifier: 'America/El_Salvador', label: '', emoji: '🏛️' },
  { id: 'sana-a', city: "Sana'a", identifier: 'Asia/Aden', label: '', emoji: '🏛️' },
  { id: 'santiago-capital', city: 'Santiago', identifier: 'America/Santiago', label: '', emoji: '🏛️' },
  { id: 'santo-domingo', city: 'Santo Domingo', identifier: 'America/Santo_Domingo', label: '', emoji: '🏛️' },
  { id: 'sarajevo', city: 'Sarajevo', identifier: 'Europe/Sarajevo', label: '', emoji: '🏛️' },
  { id: 'seoul-capital', city: 'Seoul', identifier: 'Asia/Seoul', label: '', emoji: '🏛️' },
  { id: 'singapore-capital', city: 'Singapore', identifier: 'Asia/Singapore', label: '', emoji: '🏛️' },
  { id: 'skopje', city: 'Skopje', identifier: 'Europe/Skopje', label: '', emoji: '🏛️' },
  { id: 'sofia', city: 'Sofia', identifier: 'Europe/Sofia', label: '', emoji: '🏛️' },
  { id: 'stockholm', city: 'Stockholm', identifier: 'Europe/Stockholm', label: '', emoji: '🏛️' },
  { id: 'sucre', city: 'Sucre', identifier: 'America/La_Paz', label: '', emoji: '🏛️' },
  { id: 'suva', city: 'Suva', identifier: 'Pacific/Fiji', label: '', emoji: '🏛️' },
  { id: 'tallinn', city: 'Tallinn', identifier: 'Europe/Tallinn', label: '', emoji: '🏛️' },
  { id: 'tarawa', city: 'Tarawa', identifier: 'Pacific/Tarawa', label: '', emoji: '🏛️' },
  { id: 'tashkent', city: 'Tashkent', identifier: 'Asia/Tashkent', label: '', emoji: '🏛️' },
  { id: 'tbilisi', city: 'Tbilisi', identifier: 'Asia/Tbilisi', label: '', emoji: '🏛️' },
  { id: 'tegucigalpa', city: 'Tegucigalpa', identifier: 'America/Tegucigalpa', label: '', emoji: '🏛️' },
  { id: 'tehran', city: 'Tehran', identifier: 'Asia/Tehran', label: '', emoji: '🏛️' },
  { id: 'thimphu', city: 'Thimphu', identifier: 'Asia/Thimphu', label: '', emoji: '🏛️' },
  { id: 'tirana', city: 'Tirana', identifier: 'Europe/Tirane', label: '', emoji: '🏛️' },
  { id: 'tunis', city: 'Tunis', identifier: 'Africa/Tunis', label: '', emoji: '🏛️' },
  { id: 'ulaanbaatar', city: 'Ulaanbaatar', identifier: 'Asia/Ulaanbaatar', label: '', emoji: '🏛️' },
  { id: 'vaduz', city: 'Vaduz', identifier: 'Europe/Vaduz', label: '', emoji: '🏛️' },
  { id: 'valletta', city: 'Valletta', identifier: 'Europe/Malta', label: '', emoji: '🏛️' },
  { id: 'vatican', city: 'Vatican City', identifier: 'Europe/Rome', label: '', emoji: '🏛️' },
  { id: 'victoria', city: 'Victoria', identifier: 'Indian/Mahe', label: '', emoji: '🏛️' },
  { id: 'vienna', city: 'Vienna', identifier: 'Europe/Vienna', label: '', emoji: '🏛️' },
  { id: 'vientiane', city: 'Vientiane', identifier: 'Asia/Vientiane', label: '', emoji: '🏛️' },
  { id: 'vilnius', city: 'Vilnius', identifier: 'Europe/Vilnius', label: '', emoji: '🏛️' },
  { id: 'warsaw', city: 'Warsaw', identifier: 'Europe/Warsaw', label: '', emoji: '🏛️' },
  { id: 'washington-dc', city: 'Washington, DC', identifier: 'America/New_York', label: '', emoji: '🏛️' },
  { id: 'wellington', city: 'Wellington', identifier: 'Pacific/Auckland', label: '', emoji: '🏛️' },
  { id: 'windhoek', city: 'Windhoek', identifier: 'Africa/Windhoek', label: '', emoji: '🏛️' },
  { id: 'yaounde', city: 'Yaoundé', identifier: 'Africa/Douala', label: '', emoji: '🏛️' },
  { id: 'yaren', city: 'Yaren', identifier: 'Pacific/Nauru', label: '', emoji: '🏛️' },
  { id: 'yerevan', city: 'Yerevan', identifier: 'Asia/Yerevan', label: '', emoji: '🏛️' },
  { id: 'zagreb', city: 'Zagreb', identifier: 'Europe/Zagreb', label: '', emoji: '🏛️' },
  { id: 'brunei', city: 'Bandar Seri Begawan', identifier: 'Asia/Brunei', label: '', emoji: '🏛️' },
  { id: 'noumea', city: 'Nouméa', identifier: 'Pacific/Noumea', label: '', emoji: '🏛️' },
  { id: 'kuala-lumpur', city: 'Kuala Lumpur', identifier: 'Asia/Kuala_Lumpur', label: '', emoji: '🏛️' },
  { id: 'kiev', city: 'Kyiv', identifier: 'Europe/Kyiv', label: '', emoji: '🏛️' },
  { id: 'almaty', city: 'Almaty', identifier: 'Asia/Almaty', label: '', emoji: '🏛️' },
  { id: 'dover', city: 'Doha', identifier: 'Asia/Qatar', label: '', emoji: '🏛️' },
  { id: 'bangkok-capital', city: 'Bangkok', identifier: 'Asia/Bangkok', label: '', emoji: '🏛️' },
  { id: 'jakarta-capital', city: 'Jakarta', identifier: 'Asia/Jakarta', label: '', emoji: '🏛️' },
  { id: 'manila', city: 'Manila', identifier: 'Asia/Manila', label: '', emoji: '🏛️' },
  { id: 'surabaya', city: 'Surabaya', identifier: 'Asia/Jakarta', label: '', emoji: '🏛️' },
  { id: 'taipei', city: 'Taipei', identifier: 'Asia/Taipei', label: '', emoji: '🏛️' },
  { id: 'vienna-capital', city: 'Vienna', identifier: 'Europe/Vienna', label: '', emoji: '🏛️' },
  { id: 'zagreb-capital', city: 'Zagreb', identifier: 'Europe/Zagreb', label: '', emoji: '🏛️' },
  { id: 'helsinki-capital', city: 'Helsinki', identifier: 'Europe/Helsinki', label: '', emoji: '🏛️' },
  { id: 'tashkent-capital', city: 'Tashkent', identifier: 'Asia/Tashkent', label: '', emoji: '🏛️' },
  { id: 'montevideo-capital', city: 'Montevideo', identifier: 'America/Montevideo', label: '', emoji: '🏛️' },
  { id: 'ljubljana-capital', city: 'Ljubljana', identifier: 'Europe/Ljubljana', label: '', emoji: '🏛️' },
  { id: 'reykjavik-capital', city: 'Reykjavík', identifier: 'Atlantic/Reykjavik', label: '', emoji: '🏛️' },
  { id: 'pristina', city: 'Pristina', identifier: 'Europe/Belgrade', label: '', emoji: '🏛️' },
  { id: 'belgrade', city: 'Belgrade', identifier: 'Europe/Belgrade', label: '', emoji: '🏛️' },
  { id: 'tirana-capital', city: 'Tirana', identifier: 'Europe/Tirane', label: '', emoji: '🏛️' },
  { id: 'brasilia-capital', city: 'Brasília', identifier: 'America/Sao_Paulo', label: '', emoji: '🏛️' },
  { id: 'kuwait-city', city: 'Kuwait City', identifier: 'Asia/Kuwait', label: '', emoji: '🏛️' },
  { id: 'madinah', city: 'Riyadh', identifier: 'Asia/Riyadh', label: '', emoji: '🏛️' },
  { id: 'malabo', city: 'Malabo', identifier: 'Africa/Malabo', label: '', emoji: '🏛️' },
  { id: 'porto-vila', city: 'Port Vila', identifier: 'Pacific/Efate', label: '', emoji: '🏛️' },
  { id: 'yamoussoukro', city: 'Yamoussoukro', identifier: 'Africa/Abidjan', label: '', emoji: '🏛️' },
  { id: 'zagreb-2', city: 'Zagreb', identifier: 'Europe/Zagreb', label: '', emoji: '🏛️' },
  { id: 'tbilisi-capital', city: 'Tbilisi', identifier: 'Asia/Tbilisi', label: '', emoji: '🏛️' },
  { id: 'prague-capital', city: 'Prague', identifier: 'Europe/Prague', label: '', emoji: '🏛️' },
  { id: 'sofia-capital', city: 'Sofia', identifier: 'Europe/Sofia', label: '', emoji: '🏛️' },
  { id: 'bucharest-capital', city: 'Bucharest', identifier: 'Europe/Bucharest', label: '', emoji: '🏛️' },
  { id: 'port-au-prince-capital', city: 'Port-au-Prince', identifier: 'America/Port-au-Prince', label: '', emoji: '🏛️' },
  { id: 'kingston-capital', city: 'Kingston', identifier: 'America/Jamaica', label: '', emoji: '🏛️' },
  { id: 'bogota-capital', city: 'Bogotá', identifier: 'America/Bogota', label: '', emoji: '🏛️' },
  { id: 'lima', city: 'Lima', identifier: 'America/Lima', label: '', emoji: '🏛️' },
  { id: 'asuncion', city: 'Asunción', identifier: 'America/Asuncion', label: '', emoji: '🏛️' },
  { id: 'santiago', city: 'Santiago', identifier: 'America/Santiago', label: '', emoji: '🏛️' },
  { id: 'montevideo-2', city: 'Montevideo', identifier: 'America/Montevideo', label: '', emoji: '🏛️' },
  { id: 'caracas-capital', city: 'Caracas', identifier: 'America/Caracas', label: '', emoji: '🏛️' },
  { id: 'la-paz-capital', city: 'La Paz', identifier: 'America/La_Paz', label: '', emoji: '🏛️' },
  { id: 'quito-capital', city: 'Quito', identifier: 'America/Guayaquil', label: '', emoji: '🏛️' },
  { id: 'paramaribo-capital', city: 'Paramaribo', identifier: 'America/Paramaribo', label: '', emoji: '🏛️' },
  { id: 'georgetown-capital', city: 'Georgetown', identifier: 'America/Guyana', label: '', emoji: '🏛️' },
  { id: 'sucre-capital', city: 'Sucre', identifier: 'America/La_Paz', label: '', emoji: '🏛️' },
  { id: 'baku-capital', city: 'Baku', identifier: 'Asia/Baku', label: '', emoji: '🏛️' },
  { id: 'tunis-capital', city: 'Tunis', identifier: 'Africa/Tunis', label: '', emoji: '🏛️' },
  { id: 'algiers-capital', city: 'Algiers', identifier: 'Africa/Algiers', label: '', emoji: '🏛️' },
  { id: 'lusaka-capital', city: 'Lusaka', identifier: 'Africa/Lusaka', label: '', emoji: '🏛️' },
  { id: 'harare-capital', city: 'Harare', identifier: 'Africa/Harare', label: '', emoji: '🏛️' },
  { id: 'rabat-capital', city: 'Rabat', identifier: 'Africa/Casablanca', label: '', emoji: '🏛️' },
  { id: 'tbilisi-2', city: 'Tbilisi', identifier: 'Asia/Tbilisi', label: '', emoji: '🏛️' },
  { id: 'yerevan-capital', city: 'Yerevan', identifier: 'Asia/Yerevan', label: '', emoji: '🏛️' },
  { id: 'baku-2', city: 'Baku', identifier: 'Asia/Baku', label: '', emoji: '🏛️' },
  { id: 'tallinn-capital', city: 'Tallinn', identifier: 'Europe/Tallinn', label: '', emoji: '🏛️' },
  { id: 'riga-capital', city: 'Riga', identifier: 'Europe/Riga', label: '', emoji: '🏛️' },
  { id: 'vilnius-capital', city: 'Vilnius', identifier: 'Europe/Vilnius', label: '', emoji: '🏛️' },
  { id: 'oslo-capital', city: 'Oslo', identifier: 'Europe/Oslo', label: '', emoji: '🏛️' },
  { id: 'stockholm-capital', city: 'Stockholm', identifier: 'Europe/Stockholm', label: '', emoji: '🏛️' },
  { id: 'copenhagen-capital', city: 'Copenhagen', identifier: 'Europe/Copenhagen', label: '', emoji: '🏛️' },
  { id: 'helsinki-2', city: 'Helsinki', identifier: 'Europe/Helsinki', label: '', emoji: '🏛️' },
  { id: 'london-capital', city: 'London', identifier: 'Europe/London', label: '', emoji: '🏛️' },
  { id: 'paris-capital', city: 'Paris', identifier: 'Europe/Paris', label: '', emoji: '🏛️' },
  { id: 'berlin-capital', city: 'Berlin', identifier: 'Europe/Berlin', label: '', emoji: '🏛️' },
  { id: 'rome-2', city: 'Rome', identifier: 'Europe/Rome', label: '', emoji: '🏛️' },
  { id: 'madrid-2', city: 'Madrid', identifier: 'Europe/Madrid', label: '', emoji: '🏛️' },
  { id: 'lisbon-2', city: 'Lisbon', identifier: 'Europe/Lisbon', label: '', emoji: '🏛️' },
  { id: 'vienna-2', city: 'Vienna', identifier: 'Europe/Vienna', label: '', emoji: '🏛️' },
  { id: 'budapest-2', city: 'Budapest', identifier: 'Europe/Budapest', label: '', emoji: '🏛️' },
  { id: 'prague-2', city: 'Prague', identifier: 'Europe/Prague', label: '', emoji: '🏛️' },
  { id: 'bratislava-2', city: 'Bratislava', identifier: 'Europe/Bratislava', label: '', emoji: '🏛️' },
  { id: 'warsaw-2', city: 'Warsaw', identifier: 'Europe/Warsaw', label: '', emoji: '🏛️' },
  { id: 'sofia-2', city: 'Sofia', identifier: 'Europe/Sofia', label: '', emoji: '🏛️' },
  { id: 'bucharest-2', city: 'Bucharest', identifier: 'Europe/Bucharest', label: '', emoji: '🏛️' },
  { id: 'athens-2', city: 'Athens', identifier: 'Europe/Athens', label: '', emoji: '🏛️' },
  { id: 'ankara-2', city: 'Ankara', identifier: 'Europe/Istanbul', label: '', emoji: '🏛️' },
  { id: 'baghdad-2', city: 'Baghdad', identifier: 'Asia/Baghdad', label: '', emoji: '🏛️' },
  { id: 'tehran-2', city: 'Tehran', identifier: 'Asia/Tehran', label: '', emoji: '🏛️' },
  { id: 'riyadh-2', city: 'Riyadh', identifier: 'Asia/Riyadh', label: '', emoji: '🏛️' },
  { id: 'doha-2', city: 'Doha', identifier: 'Asia/Qatar', label: '', emoji: '🏛️' },
  { id: 'muscat-2', city: 'Muscat', identifier: 'Asia/Muscat', label: '', emoji: '🏛️' },
  { id: 'manama-2', city: 'Manama', identifier: 'Asia/Bahrain', label: '', emoji: '🏛️' },
  { id: 'kuwait-city-2', city: 'Kuwait City', identifier: 'Asia/Kuwait', label: '', emoji: '🏛️' },
  { id: 'jerusalem-2', city: 'Jerusalem', identifier: 'Asia/Jerusalem', label: '', emoji: '🏛️' },
  { id: 'amman-2', city: 'Amman', identifier: 'Asia/Amman', label: '', emoji: '🏛️' },
  { id: 'beirut-2', city: 'Beirut', identifier: 'Asia/Beirut', label: '', emoji: '🏛️' },
  { id: 'damascus-2', city: 'Damascus', identifier: 'Asia/Damascus', label: '', emoji: '🏛️' },
  { id: 'kabul-2', city: 'Kabul', identifier: 'Asia/Kabul', label: '', emoji: '🏛️' },
  { id: 'islamabad-2', city: 'Islamabad', identifier: 'Asia/Karachi', label: '', emoji: '🏛️' },
  { id: 'delhi-capital', city: 'New Delhi', identifier: 'Asia/Kolkata', label: '', emoji: '🏛️' },
  { id: 'dhaka-2', city: 'Dhaka', identifier: 'Asia/Dhaka', label: '', emoji: '🏛️' },
  { id: 'colombo', city: 'Colombo', identifier: 'Asia/Colombo', label: '', emoji: '🏛️' },
  { id: 'kathmandu-2', city: 'Kathmandu', identifier: 'Asia/Kathmandu', label: '', emoji: '🏛️' },
  { id: 'thimphu-2', city: 'Thimphu', identifier: 'Asia/Thimphu', label: '', emoji: '🏛️' },
  { id: 'malé-2', city: 'Malé', identifier: 'Indian/Maldives', label: '', emoji: '🏛️' },
  { id: 'male-capital', city: 'Malé', identifier: 'Indian/Maldives', label: '', emoji: '🏛️' },
  { id: 'hanoi-2', city: 'Hanoi', identifier: 'Asia/Bangkok', label: '', emoji: '🏛️' },
  { id: 'vientiane-2', city: 'Vientiane', identifier: 'Asia/Vientiane', label: '', emoji: '🏛️' },
  { id: 'phnom-penh-2', city: 'Phnom Penh', identifier: 'Asia/Phnom_Penh', label: '', emoji: '🏛️' },
  { id: 'bangkok-2', city: 'Bangkok', identifier: 'Asia/Bangkok', label: '', emoji: '🏛️' },
  { id: 'kuala-lumpur-2', city: 'Kuala Lumpur', identifier: 'Asia/Kuala_Lumpur', label: '', emoji: '🏛️' },
  { id: 'singapore-2', city: 'Singapore', identifier: 'Asia/Singapore', label: '', emoji: '🏛️' },
  { id: 'jakarta-2', city: 'Jakarta', identifier: 'Asia/Jakarta', label: '', emoji: '🏛️' },
  { id: 'manila-2', city: 'Manila', identifier: 'Asia/Manila', label: '', emoji: '🏛️' },
  { id: 'pyongyang-2', city: 'Pyongyang', identifier: 'Asia/Pyongyang', label: '', emoji: '🏛️' },
  { id: 'seoul-2', city: 'Seoul', identifier: 'Asia/Seoul', label: '', emoji: '🏛️' },
  { id: 'tokyo-capital', city: 'Tokyo', identifier: 'Asia/Tokyo', label: '', emoji: '🏛️' },
  { id: 'beijing-capital', city: 'Beijing', identifier: 'Asia/Shanghai', label: '', emoji: '🏛️' },
  { id: 'taipei-2', city: 'Taipei', identifier: 'Asia/Taipei', label: '', emoji: '🏛️' },
  { id: 'ulaanbaatar-2', city: 'Ulaanbaatar', identifier: 'Asia/Ulaanbaatar', label: '', emoji: '🏛️' },
  { id: 'canberra-2', city: 'Canberra', identifier: 'Australia/Canberra', label: '', emoji: '🏛️' },
  { id: 'wellington-2', city: 'Wellington', identifier: 'Pacific/Auckland', label: '', emoji: '🏛️' },
  { id: 'port-moresby-2', city: 'Port Moresby', identifier: 'Pacific/Port_Moresby', label: '', emoji: '🏛️' },
  { id: 'suva-2', city: 'Suva', identifier: 'Pacific/Fiji', label: '', emoji: '🏛️' },
  { id: 'tarawa-2', city: 'Tarawa', identifier: 'Pacific/Tarawa', label: '', emoji: '🏛️' },
  { id: 'funafuti-2', city: 'Funafuti', identifier: 'Pacific/Funafuti', label: '', emoji: '🏛️' },
  { id: 'majuro-2', city: 'Majuro', identifier: 'Pacific/Majuro', label: '', emoji: '🏛️' },
  { id: 'palikir-2', city: 'Palikir', identifier: 'Pacific/Pohnpei', label: '', emoji: '🏛️' },
  { id: 'yaren-2', city: 'Yaren', identifier: 'Pacific/Nauru', label: '', emoji: '🏛️' },
  { id: 'koror', city: 'Koror', identifier: 'Pacific/Palau', label: '', emoji: '🏛️' },
  { id: 'rarotonga', city: 'Rarotonga', identifier: 'Pacific/Rarotonga', label: '', emoji: '🏛️' },
  { id: 'honiara-2', city: 'Honiara', identifier: 'Pacific/Guadalcanal', label: '', emoji: '🏛️' },
  { id: 'port-vila-2', city: 'Port Vila', identifier: 'Pacific/Efate', label: '', emoji: '🏛️' },
  { id: 'suva-capital', city: 'Suva', identifier: 'Pacific/Fiji', label: '', emoji: '🏛️' },
  { id: 'apra', city: 'Apia', identifier: 'Pacific/Apia', label: '', emoji: '🏛️' },
  { id: 'nuku-alofa-2', city: "Nuku'alofa", identifier: 'Pacific/Tongatapu', label: '', emoji: '🏛️' },
  { id: 'republic-iran', city: 'Tehran', identifier: 'Asia/Tehran', label: '', emoji: '🏛️' },
  { id: 'cape-verde', city: 'Praia', identifier: 'Atlantic/Cape_Verde', label: '', emoji: '🏛️' },
  { id: 'praia', city: 'Praia', identifier: 'Atlantic/Cape_Verde', label: '', emoji: '🏛️' },
  { id: 'bishkek', city: 'Bishkek', identifier: 'Asia/Bishkek', label: '', emoji: '🏛️' },
  { id: 'tbilisi-3', city: 'Tbilisi', identifier: 'Asia/Tbilisi', label: '', emoji: '🏛️' },
  { id: 'dushanbe-2', city: 'Dushanbe', identifier: 'Asia/Dushanbe', label: '', emoji: '🏛️' },
  { id: 'ashgabat-2', city: 'Ashgabat', identifier: 'Asia/Ashgabat', label: '', emoji: '🏛️' },
  { id: 'tashkent-2', city: 'Tashkent', identifier: 'Asia/Tashkent', label: '', emoji: '🏛️' },
  { id: 'baku-3', city: 'Baku', identifier: 'Asia/Baku', label: '', emoji: '🏛️' },
  { id: 'yerevan-2', city: 'Yerevan', identifier: 'Asia/Yerevan', label: '', emoji: '🏛️' },
  { id: 'tbilisi', city: 'Tbilisi', identifier: 'Asia/Tbilisi', label: '', emoji: '🏛️' },
  { id: 'sarajevo-2', city: 'Sarajevo', identifier: 'Europe/Sarajevo', label: '', emoji: '🏛️' },
  { id: 'skopje-2', city: 'Skopje', identifier: 'Europe/Skopje', label: '', emoji: '🏛️' },
  { id: 'podgorica-2', city: 'Podgorica', identifier: 'Europe/Podgorica', label: '', emoji: '🏛️' },
  { id: 'tirana-2', city: 'Tirana', identifier: 'Europe/Tirane', label: '', emoji: '🏛️' },
  { id: 'brussels-2', city: 'Brussels', identifier: 'Europe/Brussels', label: '', emoji: '🏛️' },
  { id: 'luxembourg-2', city: 'Luxembourg', identifier: 'Europe/Luxembourg', label: '', emoji: '🏛️' },
  { id: 'monaco-2', city: 'Monaco', identifier: 'Europe/Monaco', label: '', emoji: '🏛️' },
  { id: 'bern-2', city: 'Bern', identifier: 'Europe/Zurich', label: '', emoji: '🏛️' },
  { id: 'vat', city: 'Vatican City', identifier: 'Europe/Rome', label: '', emoji: '🏛️' },
  { id: 'san-marino-2', city: 'San Marino', identifier: 'Europe/San_Marino', label: '', emoji: '🏛️' },
  { id: 'vatican-2', city: 'Vatican City', identifier: 'Europe/Rome', label: '', emoji: '🏛️' },
  { id: 'andorra', city: 'Andorra la Vella', identifier: 'Europe/Andorra', label: '', emoji: '🏛️' },
  { id: 'lisbon-capital', city: 'Lisbon', identifier: 'Europe/Lisbon', label: '', emoji: '🏛️' },
  { id: 'madrid-capital-2', city: 'Madrid', identifier: 'Europe/Madrid', label: '', emoji: '🏛️' },
  { id: 'rome-capital-2', city: 'Rome', identifier: 'Europe/Rome', label: '', emoji: '🏛️' },
  { id: 'paris-capital-2', city: 'Paris', identifier: 'Europe/Paris', label: '', emoji: '🏛️' },
  { id: 'berlin-capital-2', city: 'Berlin', identifier: 'Europe/Berlin', label: '', emoji: '🏛️' },
  { id: 'london-capital-2', city: 'London', identifier: 'Europe/London', label: '', emoji: '🏛️' },
  { id: 'dublin-capital-2', city: 'Dublin', identifier: 'Europe/Dublin', label: '', emoji: '🏛️' },
  { id: 'reykjavik-2', city: 'Reykjavík', identifier: 'Atlantic/Reykjavik', label: '', emoji: '🏛️' },
  { id: 'tallinn-2', city: 'Tallinn', identifier: 'Europe/Tallinn', label: '', emoji: '🏛️' },
  { id: 'riga-2', city: 'Riga', identifier: 'Europe/Riga', label: '', emoji: '🏛️' },
  { id: 'vilnius-2', city: 'Vilnius', identifier: 'Europe/Vilnius', label: '', emoji: '🏛️' },
  { id: 'warsaw-capital', city: 'Warsaw', identifier: 'Europe/Warsaw', label: '', emoji: '🏛️' },
  { id: 'prague-capital-2', city: 'Prague', identifier: 'Europe/Prague', label: '', emoji: '🏛️' },
  { id: 'vienna-capital-2', city: 'Vienna', identifier: 'Europe/Vienna', label: '', emoji: '🏛️' },
  { id: 'bratislava-capital', city: 'Bratislava', identifier: 'Europe/Bratislava', label: '', emoji: '🏛️' },
  { id: 'budapest-capital', city: 'Budapest', identifier: 'Europe/Budapest', label: '', emoji: '🏛️' },
  { id: 'bucharest-capital-3', city: 'Bucharest', identifier: 'Europe/Bucharest', label: '', emoji: '🏛️' },
  { id: 'sofia-capital-3', city: 'Sofia', identifier: 'Europe/Sofia', label: '', emoji: '🏛️' },
  { id: 'athens-capital', city: 'Athens', identifier: 'Europe/Athens', label: '', emoji: '🏛️' },
  { id: 'ankara-capital', city: 'Ankara', identifier: 'Europe/Istanbul', label: '', emoji: '🏛️' },
  { id: 'jerusalem-capital', city: 'Jerusalem', identifier: 'Asia/Jerusalem', label: '', emoji: '🏛️' },
  { id: 'amman-capital', city: 'Amman', identifier: 'Asia/Amman', label: '', emoji: '🏛️' },
  { id: 'beirut-capital', city: 'Beirut', identifier: 'Asia/Beirut', label: '', emoji: '🏛️' },
  { id: 'damascus-capital', city: 'Damascus', identifier: 'Asia/Damascus', label: '', emoji: '🏛️' },
  { id: 'baghdad-capital', city: 'Baghdad', identifier: 'Asia/Baghdad', label: '', emoji: '🏛️' },
  { id: 'tehran-capital', city: 'Tehran', identifier: 'Asia/Tehran', label: '', emoji: '🏛️' },
  { id: 'riyadh-capital', city: 'Riyadh', identifier: 'Asia/Riyadh', label: '', emoji: '🏛️' },
  { id: 'doha-capital', city: 'Doha', identifier: 'Asia/Qatar', label: '', emoji: '🏛️' },
  { id: 'kuwait-capital', city: 'Kuwait City', identifier: 'Asia/Kuwait', label: '', emoji: '🏛️' },
  { id: 'muscat-capital', city: 'Muscat', identifier: 'Asia/Muscat', label: '', emoji: '🏛️' },
  { id: 'manama-capital', city: 'Manama', identifier: 'Asia/Bahrain', label: '', emoji: '🏛️' },
  { id: 'abu-dhabi-capital', city: 'Abu Dhabi', identifier: 'Asia/Dubai', label: '', emoji: '🏛️' },
  { id: 'doha-capital-2', city: 'Doha', identifier: 'Asia/Qatar', label: '', emoji: '🏛️' },
  { id: 'kabul-capital', city: 'Kabul', identifier: 'Asia/Kabul', label: '', emoji: '🏛️' },
  { id: 'islamabad-capital', city: 'Islamabad', identifier: 'Asia/Karachi', label: '', emoji: '🏛️' },
  { id: 'new-delhi', city: 'New Delhi', identifier: 'Asia/Kolkata', label: '', emoji: '🏛️' },
  { id: 'kathmandu-capital', city: 'Kathmandu', identifier: 'Asia/Kathmandu', label: '', emoji: '🏛️' },
  { id: 'thimphu-capital', city: 'Thimphu', identifier: 'Asia/Thimphu', label: '', emoji: '🏛️' },
  { id: 'dhaka-capital', city: 'Dhaka', identifier: 'Asia/Dhaka', label: '', emoji: '🏛️' },
  { id: 'colombo-capital', city: 'Colombo', identifier: 'Asia/Colombo', label: '', emoji: '🏛️' },
  { id: 'male-capital-2', city: 'Malé', identifier: 'Indian/Maldives', label: '', emoji: '🏛️' },
  { id: 'yangon', city: 'Yangon', identifier: 'Asia/Yangon', label: '', emoji: '🏛️' },
  { id: 'bangkok-capital-3', city: 'Bangkok', identifier: 'Asia/Bangkok', label: '', emoji: '🏛️' },
  { id: 'vientiane-capital', city: 'Vientiane', identifier: 'Asia/Vientiane', label: '', emoji: '🏛️' },
  { id: 'phnom-penh-capital', city: 'Phnom Penh', identifier: 'Asia/Phnom_Penh', label: '', emoji: '🏛️' },
  { id: 'hanoi-capital', city: 'Hanoi', identifier: 'Asia/Bangkok', label: '', emoji: '🏛️' },
  { id: 'kuala-lumpur-capital', city: 'Kuala Lumpur', identifier: 'Asia/Kuala_Lumpur', label: '', emoji: '🏛️' },
  { id: 'singapore-capital-2', city: 'Singapore', identifier: 'Asia/Singapore', label: '', emoji: '🏛️' },
  { id: 'jakarta-capital-2', city: 'Jakarta', identifier: 'Asia/Jakarta', label: '', emoji: '🏛️' },
  { id: 'manila-capital', city: 'Manila', identifier: 'Asia/Manila', label: '', emoji: '🏛️' },
  { id: 'taipei-capital', city: 'Taipei', identifier: 'Asia/Taipei', label: '', emoji: '🏛️' },
  { id: 'tokyo-capital-2', city: 'Tokyo', identifier: 'Asia/Tokyo', label: '', emoji: '🏛️' },
  { id: 'seoul-capital-2', city: 'Seoul', identifier: 'Asia/Seoul', label: '', emoji: '🏛️' },
  { id: 'pyongyang-capital', city: 'Pyongyang', identifier: 'Asia/Pyongyang', label: '', emoji: '🏛️' },
  { id: 'beijing-capital-2', city: 'Beijing', identifier: 'Asia/Shanghai', label: '', emoji: '🏛️' },
  { id: 'ulaanbaatar-capital', city: 'Ulaanbaatar', identifier: 'Asia/Ulaanbaatar', label: '', emoji: '🏛️' },
  { id: 'canberra-capital', city: 'Canberra', identifier: 'Australia/Canberra', label: '', emoji: '🏛️' },
  { id: 'wellington-capital', city: 'Wellington', identifier: 'Pacific/Auckland', label: '', emoji: '🏛️' },
  { id: 'suva-capital-2', city: 'Suva', identifier: 'Pacific/Fiji', label: '', emoji: '🏛️' },
  { id: 'port-moresby-capital', city: 'Port Moresby', identifier: 'Pacific/Port_Moresby', label: '', emoji: '🏛️' },
  { id: 'honiara-capital', city: 'Honiara', identifier: 'Pacific/Guadalcanal', label: '', emoji: '🏛️' },
  { id: 'port-vila-capital', city: 'Port Vila', identifier: 'Pacific/Efate', label: '', emoji: '🏛️' },
  { id: 'tarawa-capital', city: 'Tarawa', identifier: 'Pacific/Tarawa', label: '', emoji: '🏛️' },
  { id: 'funafuti-capital', city: 'Funafuti', identifier: 'Pacific/Funafuti', label: '', emoji: '🏛️' },
  { id: 'majuro-capital', city: 'Majuro', identifier: 'Pacific/Majuro', label: '', emoji: '🏛️' },
  { id: 'palikir-capital', city: 'Palikir', identifier: 'Pacific/Pohnpei', label: '', emoji: '🏛️' },
  { id: 'yaren-capital', city: 'Yaren', identifier: 'Pacific/Nauru', label: '', emoji: '🏛️' },
  { id: 'koror-capital', city: 'Koror', identifier: 'Pacific/Palau', label: '', emoji: '🏛️' },
  { id: 'rarotonga-capital', city: 'Rarotonga', identifier: 'Pacific/Rarotonga', label: '', emoji: '🏛️' },
  { id: 'noumea-capital', city: 'Nouméa', identifier: 'Pacific/Noumea', label: '', emoji: '🏛️' },
  { id: 'apra-capital', city: 'Apia', identifier: 'Pacific/Apia', label: '', emoji: '🏛️' },
  { id: 'nuku-alofa-capital', city: "Nuku'alofa", identifier: 'Pacific/Tongatapu', label: '', emoji: '🏛️' },
  { id: 'havana-capital', city: 'Havana', identifier: 'America/Havana', label: '', emoji: '🏛️' },
  { id: 'nassau-capital', city: 'Nassau', identifier: 'America/Nassau', label: '', emoji: '🏛️' },
  { id: 'kingston-2', city: 'Kingston', identifier: 'America/Jamaica', label: '', emoji: '🏛️' },
  { id: 'port-of-spain-2', city: 'Port of Spain', identifier: 'America/Port_of_Spain', label: '', emoji: '🏛️' },
  { id: 'bridgetown-2', city: 'Bridgetown', identifier: 'America/Barbados', label: '', emoji: '🏛️' },
  { id: 'roseau-2', city: 'Roseau', identifier: 'America/Dominica', label: '', emoji: '🏛️' },
  { id: 'castries-2', city: 'Castries', identifier: 'America/St_Lucia', label: '', emoji: '🏛️' },
  { id: 'st-johns', city: "St. John's", identifier: 'America/Antigua', label: '', emoji: '🏛️' },
  { id: 'kingstown-2', city: 'Kingstown', identifier: 'America/St_Vincent', label: '', emoji: '🏛️' },
  { id: 'basseterre-2', city: 'Basseterre', identifier: 'America/St_Kitts', label: '', emoji: '🏛️' },
  { id: 'santo-domingo-2', city: 'Santo Domingo', identifier: 'America/Santo_Domingo', label: '', emoji: '🏛️' },
  { id: 'san-juan', city: 'San Juan', identifier: 'America/Puerto_Rico', label: '', emoji: '🏛️' },
  { id: 'guatemala-city-2', city: 'Guatemala City', identifier: 'America/Guatemala', label: '', emoji: '🏛️' },
  { id: 'belmopan-2', city: 'Belmopan', identifier: 'America/Belize', label: '', emoji: '🏛️' },
  { id: 'san-salvador-2', city: 'San Salvador', identifier: 'America/El_Salvador', label: '', emoji: '🏛️' },
  { id: 'tegucigalpa-2', city: 'Tegucigalpa', identifier: 'America/Tegucigalpa', label: '', emoji: '🏛️' },
  { id: 'managua-2', city: 'Managua', identifier: 'America/Managua', label: '', emoji: '🏛️' },
  { id: 'san-jose-2', city: 'San José', identifier: 'America/Costa_Rica', label: '', emoji: '🏛️' },
  { id: 'panama-city-2', city: 'Panama City', identifier: 'America/Panama', label: '', emoji: '🏛️' },
  { id: 'washington-dc-2', city: 'Washington, DC', identifier: 'America/New_York', label: '', emoji: '🏛️' },
  { id: 'ottawa-2', city: 'Ottawa', identifier: 'America/Toronto', label: '', emoji: '🏛️' },
  { id: 'bogota-2', city: 'Bogotá', identifier: 'America/Bogota', label: '', emoji: '🏛️' },
  { id: 'caracas-2', city: 'Caracas', identifier: 'America/Caracas', label: '', emoji: '🏛️' },
  { id: 'quito-2', city: 'Quito', identifier: 'America/Guayaquil', label: '', emoji: '🏛️' },
  { id: 'lima-2', city: 'Lima', identifier: 'America/Lima', label: '', emoji: '🏛️' },
  { id: 'la-paz-2', city: 'La Paz', identifier: 'America/La_Paz', label: '', emoji: '🏛️' },
  { id: 'asuncion-2', city: 'Asunción', identifier: 'America/Asuncion', label: '', emoji: '🏛️' },
  { id: 'montevideo-3', city: 'Montevideo', identifier: 'America/Montevideo', label: '', emoji: '🏛️' },
  { id: 'georgetown-2', city: 'Georgetown', identifier: 'America/Guyana', label: '', emoji: '🏛️' },
  { id: 'paramaribo-2', city: 'Paramaribo', identifier: 'America/Paramaribo', label: '', emoji: '🏛️' },
  { id: 'brasilia-2', city: 'Brasília', identifier: 'America/Sao_Paulo', label: '', emoji: '🏛️' },
  { id: 'santiago-2', city: 'Santiago', identifier: 'America/Santiago', label: '', emoji: '🏛️' },
  { id: 'buenos-aires-2', city: 'Buenos Aires', identifier: 'America/Argentina/Buenos_Aires', label: '', emoji: '🏛️' },
  { id: 'montevideo-4', city: 'Montevideo', identifier: 'America/Montevideo', label: '', emoji: '🏛️' },
  { id: 'port-au-prince-2', city: 'Port-au-Prince', identifier: 'America/Port-au-Prince', label: '', emoji: '🏛️' },
  { id: 'kingston-3', city: 'Kingston', identifier: 'America/Jamaica', label: '', emoji: '🏛️' },
  { id: 'tunis-2', city: 'Tunis', identifier: 'Africa/Tunis', label: '', emoji: '🏛️' },
  { id: 'tripoli', city: 'Tripoli', identifier: 'Africa/Tripoli', label: '', emoji: '🏛️' },
  { id: 'algiers-2', city: 'Algiers', identifier: 'Africa/Algiers', label: '', emoji: '🏛️' },
  { id: 'rabat-2', city: 'Rabat', identifier: 'Africa/Casablanca', label: '', emoji: '🏛️' },
  { id: 'nouakchott-2', city: 'Nouakchott', identifier: 'Africa/Nouakchott', label: '', emoji: '🏛️' },
  { id: 'dakar-2', city: 'Dakar', identifier: 'Africa/Dakar', label: '', emoji: '🏛️' },
  { id: 'banjul-2', city: 'Banjul', identifier: 'Africa/Banjul', label: '', emoji: '🏛️' },
  { id: 'conakry-2', city: 'Conakry', identifier: 'Africa/Conakry', label: '', emoji: '🏛️' },
  { id: 'bissau-2', city: 'Bissau', identifier: 'Africa/Bissau', label: '', emoji: '🏛️' },
  { id: 'freetown-2', city: 'Freetown', identifier: 'Africa/Freetown', label: '', emoji: '🏛️' },
  { id: 'monrovia-2', city: 'Monrovia', identifier: 'Africa/Monrovia', label: '', emoji: '🏛️' },
  { id: 'accra-2', city: 'Accra', identifier: 'Africa/Accra', label: '', emoji: '🏛️' },
  { id: 'abidjan', city: 'Abidjan', identifier: 'Africa/Abidjan', label: '', emoji: '🏛️' },
  { id: 'yamoussoukro-2', city: 'Yamoussoukro', identifier: 'Africa/Abidjan', label: '', emoji: '🏛️' },
  { id: 'bamako-2', city: 'Bamako', identifier: 'Africa/Bamako', label: '', emoji: '🏛️' },
  { id: 'ouagadougou-2', city: 'Ouagadougou', identifier: 'Africa/Ouagadougou', label: '', emoji: '🏛️' },
  { id: 'porto-novo-2', city: 'Porto-Novo', identifier: 'Africa/Porto-Novo', label: '', emoji: '🏛️' },
  { id: 'lome-2', city: 'Lomé', identifier: 'Africa/Lome', label: '', emoji: '🏛️' },
  { id: 'lagos', city: 'Lagos', identifier: 'Africa/Lagos', label: '', emoji: '🏛️' },
  { id: 'abuja-2', city: 'Abuja', identifier: 'Africa/Lagos', label: '', emoji: '🏛️' },
  { id: 'yaounde-2', city: 'Yaoundé', identifier: 'Africa/Douala', label: '', emoji: '🏛️' },
  { id: 'malabo-2', city: 'Malabo', identifier: 'Africa/Malabo', label: '', emoji: '🏛️' },
  { id: 'libreville-2', city: 'Libreville', identifier: 'Africa/Libreville', label: '', emoji: '🏛️' },
  { id: 'bangui-2', city: 'Bangui', identifier: 'Africa/Bangui', label: '', emoji: '🏛️' },
  { id: 'brazzaville', city: 'Brazzaville', identifier: 'Africa/Brazzaville', label: '', emoji: '🏛️' },
  { id: 'kinshasa-2', city: 'Kinshasa', identifier: 'Africa/Kinshasa', label: '', emoji: '🏛️' },
  { id: 'luanda', city: 'Luanda', identifier: 'Africa/Luanda', label: '', emoji: '🏛️' },
  { id: 'lusaka-2', city: 'Lusaka', identifier: 'Africa/Lusaka', label: '', emoji: '🏛️' },
  { id: 'harare-2', city: 'Harare', identifier: 'Africa/Harare', label: '', emoji: '🏛️' },
  { id: 'maputo-2', city: 'Maputo', identifier: 'Africa/Maputo', label: '', emoji: '🏛️' },
  { id: 'mbabane-2', city: 'Mbabane', identifier: 'Africa/Mbabane', label: '', emoji: '🏛️' },
  { id: 'maseru-2', city: 'Maseru', identifier: 'Africa/Maseru', label: '', emoji: '🏛️' },
  { id: 'pretoria-2', city: 'Pretoria', identifier: 'Africa/Johannesburg', label: '', emoji: '🏛️' },
  { id: 'windhoek-2', city: 'Windhoek', identifier: 'Africa/Windhoek', label: '', emoji: '🏛️' },
  { id: 'gaborone-2', city: 'Gaborone', identifier: 'Africa/Gaborone', label: '', emoji: '🏛️' },
  { id: 'kigali-2', city: 'Kigali', identifier: 'Africa/Kigali', label: '', emoji: '🏛️' },
  { id: 'kampala-2', city: 'Kampala', identifier: 'Africa/Kampala', label: '', emoji: '🏛️' },
  { id: 'juba', city: 'Juba', identifier: 'Africa/Juba', label: '', emoji: '🏛️' },
  { id: 'khartoum-2', city: 'Khartoum', identifier: 'Africa/Khartoum', label: '', emoji: '🏛️' },
  { id: 'addis-ababa-2', city: 'Addis Ababa', identifier: 'Africa/Addis_Ababa', label: '', emoji: '🏛️' },
  { id: 'asmara-2', city: 'Asmara', identifier: 'Africa/Asmara', label: '', emoji: '🏛️' },
  { id: 'djibouti-2', city: 'Djibouti', identifier: 'Africa/Djibouti', label: '', emoji: '🏛️' },
  { id: 'mogadishu-2', city: 'Mogadishu', identifier: 'Africa/Mogadishu', label: '', emoji: '🏛️' },
  { id: 'nairobi-2', city: 'Nairobi', identifier: 'Africa/Nairobi', label: '', emoji: '🏛️' },
  { id: 'dodoma-2', city: 'Dodoma', identifier: 'Africa/Dar_es_Salaam', label: '', emoji: '🏛️' },
  { id: 'lilongwe-2', city: 'Lilongwe', identifier: 'Africa/Blantyre', label: '', emoji: '🏛️' },
  { id: 'antananarivo-2', city: 'Antananarivo', identifier: 'Indian/Antananarivo', label: '', emoji: '🏛️' },
  { id: 'moroni', city: 'Moroni', identifier: 'Indian/Comoro', label: '', emoji: '🏛️' },
  { id: 'port-louis-2', city: 'Port Louis', identifier: 'Indian/Mauritius', label: '', emoji: '🏛️' },
  { id: 'victoria-2', city: 'Victoria', identifier: 'Indian/Mahe', label: '', emoji: '🏛️' },
  { id: 'sao-tome', city: 'São Tomé', identifier: 'Africa/Sao_Tome', label: '', emoji: '🏛️' },
  { id: 'praia-2', city: 'Praia', identifier: 'Atlantic/Cape_Verde', label: '', emoji: '🏛️' },
  { id: 'riyadh-capital-2', city: 'Riyadh', identifier: 'Asia/Riyadh', label: '', emoji: '🏛️' },
  { id: 'doha-capital-3', city: 'Doha', identifier: 'Asia/Qatar', label: '', emoji: '🏛️' },
  { id: 'amman-capital-2', city: 'Amman', identifier: 'Asia/Amman', label: '', emoji: '🏛️' },
  { id: 'jerusalem-capital-2', city: 'Jerusalem', identifier: 'Asia/Jerusalem', label: '', emoji: '🏛️' },
  { id: 'abu-dhabi-capital-2', city: 'Abu Dhabi', identifier: 'Asia/Dubai', label: '', emoji: '🏛️' },
  { id: 'muscat-capital-2', city: 'Muscat', identifier: 'Asia/Muscat', label: '', emoji: '🏛️' },
  { id: 'kuwait-city-capital', city: 'Kuwait City', identifier: 'Asia/Kuwait', label: '', emoji: '🏛️' },
  { id: 'manama-capital-2', city: 'Manama', identifier: 'Asia/Bahrain', label: '', emoji: '🏛️' },
  { id: 'doha-capital-4', city: 'Doha', identifier: 'Asia/Qatar', label: '', emoji: '🏛️' },
  { id: 'sanaa-capital', city: "Sana'a", identifier: 'Asia/Aden', label: '', emoji: '🏛️' },
  { id: 'baghdad-capital-2', city: 'Baghdad', identifier: 'Asia/Baghdad', label: '', emoji: '🏛️' },
  { id: 'tehran-capital-2', city: 'Tehran', identifier: 'Asia/Tehran', label: '', emoji: '🏛️' },
  { id: 'baku-capital-2', city: 'Baku', identifier: 'Asia/Baku', label: '', emoji: '🏛️' },
  { id: 'tbilisi-capital-2', city: 'Tbilisi', identifier: 'Asia/Tbilisi', label: '', emoji: '🏛️' },
  { id: 'yerevan-capital-3', city: 'Yerevan', identifier: 'Asia/Yerevan', label: '', emoji: '🏛️' },
  { id: 'tashkent-capital-2', city: 'Tashkent', identifier: 'Asia/Tashkent', label: '', emoji: '🏛️' },
  { id: 'bishkek-capital', city: 'Bishkek', identifier: 'Asia/Bishkek', label: '', emoji: '🏛️' },
  { id: 'dushanbe-capital', city: 'Dushanbe', identifier: 'Asia/Dushanbe', label: '', emoji: '🏛️' },
  { id: 'ashgabat-capital', city: 'Ashgabat', identifier: 'Asia/Ashgabat', label: '', emoji: '🏛️' },
  { id: 'astana-capital', city: 'Astana', identifier: 'Asia/Almaty', label: '', emoji: '🏛️' },
  { id: 'ulaanbaatar-capital-2', city: 'Ulaanbaatar', identifier: 'Asia/Ulaanbaatar', label: '', emoji: '🏛️' },
  { id: 'pyongyang-capital-2', city: 'Pyongyang', identifier: 'Asia/Pyongyang', label: '', emoji: '🏛️' },
  { id: 'seoul-capital-3', city: 'Seoul', identifier: 'Asia/Seoul', label: '', emoji: '🏛️' },
  { id: 'tokyo-capital-3', city: 'Tokyo', identifier: 'Asia/Tokyo', label: '', emoji: '🏛️' },
  { id: 'beijing-capital-3', city: 'Beijing', identifier: 'Asia/Shanghai', label: '', emoji: '🏛️' },
  { id: 'taipei-capital-2', city: 'Taipei', identifier: 'Asia/Taipei', label: '', emoji: '🏛️' },
  { id: 'canberra-capital-2', city: 'Canberra', identifier: 'Australia/Canberra', label: '', emoji: '🏛️' },
  { id: 'wellington-capital-2', city: 'Wellington', identifier: 'Pacific/Auckland', label: '', emoji: '🏛️' },
  { id: 'suva-capital-3', city: 'Suva', identifier: 'Pacific/Fiji', label: '', emoji: '🏛️' },
  { id: 'port-moresby-capital-2', city: 'Port Moresby', identifier: 'Pacific/Port_Moresby', label: '', emoji: '🏛️' },
  { id: 'honiara-capital-2', city: 'Honiara', identifier: 'Pacific/Guadalcanal', label: '', emoji: '🏛️' },
  { id: 'port-vila-capital-2', city: 'Port Vila', identifier: 'Pacific/Efate', label: '', emoji: '🏛️' },
  { id: 'tarawa-capital-2', city: 'Tarawa', identifier: 'Pacific/Tarawa', label: '', emoji: '🏛️' },
  { id: 'funafuti-capital-2', city: 'Funafuti', identifier: 'Pacific/Funafuti', label: '', emoji: '🏛️' },
  { id: 'majuro-capital-2', city: 'Majuro', identifier: 'Pacific/Majuro', label: '', emoji: '🏛️' },
  { id: 'palikir-capital-2', city: 'Palikir', identifier: 'Pacific/Pohnpei', label: '', emoji: '🏛️' },
  { id: 'yaren-capital-2', city: 'Yaren', identifier: 'Pacific/Nauru', label: '', emoji: '🏛️' },
  { id: 'koror-capital-2', city: 'Koror', identifier: 'Pacific/Palau', label: '', emoji: '🏛️' },
  { id: 'rarotonga-capital-2', city: 'Rarotonga', identifier: 'Pacific/Rarotonga', label: '', emoji: '🏛️' },
]

export function getBackgroundColor(date: Date, timeZone: string): string[] {
  const formatter = new Intl.DateTimeFormat('en-US', {
    timeZone,
    hour: 'numeric',
    minute: 'numeric',
    hour12: false,
  })

  const parts = formatter.formatToParts(date)
  const hour = parseInt(parts.find(p => p.type === 'hour')?.value || '12')
  const minute = parseInt(parts.find(p => p.type === 'minute')?.value || '0')
  const hourDecimal = hour + minute / 60

  // Calculate brightness
  const normalizedHour = hourDecimal / 24
  const brightness = (Math.cos((normalizedHour - 0.5) * 2 * Math.PI) + 1) / 2

  if (brightness > 0.7) {
    return ['#F2F2F9', '#E8E8F5']
  } else if (brightness > 0.4) {
    return ['#FFD9B3', '#FFBFD9']
  } else if (brightness > 0.3) {
    return ['#667799', '#997799']
  } else {
    return ['#262A40', '#333A59']
  }
}

export function getTextColor(date: Date, timeZone: string): string {
  const formatter = new Intl.DateTimeFormat('en-US', {
    timeZone,
    hour: 'numeric',
    minute: 'numeric',
    hour12: false,
  })

  const parts = formatter.formatToParts(date)
  const hour = parseInt(parts.find(p => p.type === 'hour')?.value || '12')
  const minute = parseInt(parts.find(p => p.type === 'minute')?.value || '0')
  const hourDecimal = hour + minute / 60

  const normalizedHour = hourDecimal / 24
  const brightness = (Math.cos((normalizedHour - 0.5) * 2 * Math.PI) + 1) / 2

  return brightness > 0.5 ? '#000000' : '#FFFFFF'
}
